### ISSUE TITLE
[cgrep-clang] new version for `clang<=13` + some refactoring.

### ISSUE THREAD

**Issue by bartoszek** [schra/pkgbuilds#2]
New version of `cgrep-clang` supporting `clang<=13` just doped https://github.com/terminaldweller/cgrep/issues/18
I've made a patch with sam mild refactoring making the PAKBUILD conform with AUR Guidelines, apply if you like it 😏 
http://ix.io/3t3B (`git am -s < <(curl -s http://ix.io/3t3B)`)

**Comment by schra** [comment]
Thanks for the diff. I'd happily accept your changes, if you open a PR for them.

Regarding your third commit:
* Could you elaborate what exactly wasn't confirming to the AUR guidelines beforehand? Are you referring to the `make` command being in `package()` and not `build()`?
* Why did you change `arch=(any)`? I mean, shouldn't it also work under e.g. ARM? (There is an ARM Arch distro)
* Where exactly did you "bring back `libclang.patch` required for clang:12" in the commit?

**Comment by schra** [comment]
I've now implemented some of your proposed changes myself. I'll fix `cgrep-clang-git` as soon as https://github.com/terminaldweller/cgrep/issues/19 is fixed. As I already said, if you want to contribute, please go ahead and open PRs :) I'll close this issue for now
